//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public int IdStatus { get; set; }
        public int IdClient { get; set; }
        public int IdAssortment { get; set; }
    
        public virtual Assortment Assortment { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Status Status { get; set; }
    }
}
